### ISSUE TITLE
Verify that block hash consistency is checked at end of each scenario run

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Norma#271]

**Comment by kjezek** [comment]
This check is still present in recent version and it is executed:

https://github.com/Fantom-foundation/Norma/blob/main/driver/norma/run.go#L227-L236

<img width="719" alt="image" src="https://github.com/user-attachments/assets/8411c7d6-dd85-47b2-a92a-496aef7ff847">
<img width="839" alt="image" src="https://github.com/user-attachments/assets/760799e5-598f-425c-9374-e4ec1e515406">

**Comment by kjezek** [comment]
Following properties are checked:
```

type blockHashes struct {
	Hash         common.Hash
	StateRoot    common.Hash
	ReceiptsRoot common.Hash
}

func getBlockHashes(rpcClient rpc.RpcClient, blockNumber uint64) (*blockHashes, error) {
	var block *blockHashes
	err := rpcClient.Call(&block, "eth_getBlockByNumber", hexutil.EncodeUint64(blockNumber), false)
	if err != nil {
		return nil, fmt.Errorf("failed to get block state root from RPC; %v", err)
	}
	return block, nil
}

```
